AWSTemplateFormatVersion: '2010-09-09'
Description: > 
            CloudFormation template for EC2 instance with custom security group
            and custom ssh key

Resources:
  MyEC2InstanceUbuntu:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t3.micro
      ImageId: ami-01dd271720c1ba44f # This is a placeholder AMI ID, replace with your desired AMI ID.
      KeyName: ansible-workshop  # Ensure this key pair exists in your region
      SecurityGroups:
        - !Ref MySecurityGroup
      Tags:
          - Value: "awsninja14-ubuntu"
            Key: Name
          - Value: ubuntu
            Key: login_name
            

  MyEC2InstanceAmazon:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t3.micro
      ImageId: ami-057b6e529186a8233 # This is a placeholder AMI ID, replace with your desired AMI ID.
      KeyName: ansible-workshop  # Ensure this key pair exists in your region
      SecurityGroups:
        - !Ref MySecurityGroup
      Tags:
          - Value: "awsninja14-amz"
            Key: Name
          - Value: ec2-user
            Key: login_name

  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Custom Security Group for MyEC2Instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0        # Open to the world for demonstration purposes. Modify or restrict as needed.