# Circular Dependencies for resource SourceBucket with ReplicationRule
# To avoid a circular dep. the role's policy should be declared as a 
# separate res.

Resources:
  SourceBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      VersioningConfiguration:
        Status: Enabled
      ReplicationConfiguration:
        Role: !GetAtt ReplicationRole.Arn
        Rules:
        - Id: ReplicateAll
          Prefix: ''
          Status: Enabled
          Destination:
            # I3042 hardcoded Partition in ARN
            Bucket: !Sub "arn:aws:s3:::${DestinationBucket}"

  DestinationBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      VersioningConfiguration:
        Status: Enabled

  ReplicationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: s3.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: ReplicationPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:GetObjectVersionForReplication
            - s3:GetObjectVersionAcl
            - s3:ListBucket
            Resource:
            - !Sub "arn:aws:s3:::${SourceBucket}"
            - !Sub "arn:aws:s3:::${SourceBucket}/*"
          - Effect: Allow
            Action:
            - s3:ReplicateObject
            - s3:ReplicateDelete
            Resource: !Sub "arn:aws:s3:::${DestinationBucket}/*"

Outputs:
  SourceBucketName:
    Description: "Source S3 bucket name"
    Value: !Ref SourceBucket
  DestinationBucketName:
    Description: "Destination S3 bucket name"
    Value: !Ref DestinationBucket
