Parameters:
  # jut to make things simple and avoid hardcoded AMI ID
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: 't3.micro'
      ImageId: !Ref LatestAmiId

Outputs:
     EC2PublicDNS:
      Description: 'Public DNS of EC2 instance'
      Value: !GetAtt EC2Instance.PublicDnsName