Parameters:
  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues:
         - t2.micro
         - t3.micro
    Description: "Enter t2.micro or t3.micro. Default is t3.micro"

Resources:
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      # Remember that ami ID is regional
      ImageId: ami-065681da47fb4e433
