AWSTemplateFormatVersion: '2010-09-09'
Description: > 
            CloudFormation template for EC2 instance with custom security group
            and custom ssh key

Resources:
  MyEC2InstanceUbuntu:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0989fb15ce71ba39e # This is a placeholder AMI ID, replace with your desired AMI ID.
      KeyName: !Ref ImportedKeyPair  # Ensure this key pair exists in your region
      SecurityGroups:
        - !Ref MySecurityGroup
      Tags:
          - Value: "myUbuntu"
            Key: Name
          - Value: ubuntu
            Key: login_name
            

  MyEC2InstanceAmazon:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t3.micro
      ImageId: ami-065681da47fb4e433 # This is a placeholder AMI ID, replace with your desired AMI ID.
      KeyName: !Ref ImportedKeyPair  # Ensure this key pair exists in your region
      SecurityGroups:
        - !Ref MySecurityGroup
      Tags:
          - Value: "myAmazon"
            Key: Name
          - Value: ec2-user
            Key: login_name

  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Custom Security Group for MyEC2Instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0        # Open to the world for demonstration purposes. Modify or restrict as needed.

  ImportedKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: neptun-id_ed25519-cfn
      PublicKeyMaterial: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP2i1FXlzZl/RKad5ND44aDMgC+ruU4vi0tgM5kRtvqX dudek.v@gmail.com

# FIXIT: Add second ec2 and provide correct naming
Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref MyEC2InstanceUbuntu

  SecurityGroupId:
    Description: Security Group ID
    Value: !Ref MySecurityGroup
